# Request
query getStations {
  getStations(
    filters: {
    	latitude: 34.156839
    	longitude: -118.434454
      distanceUnit: "mi"
      distanceRadius: 5
      plugTypes: ["CHAdeMO", "CCS"]
    },
     sortBy: {
      distanceToStation: "asc"
    },
    pagination: {
      size: 10
      from: 0
    }
  ){
    found
   	stations{
      id
      access
      address
      city
      country
      description
      distanceToStation
      distanceUnit
      latitude
      longitude
      openingHours
      phoneNumber
      postcode
      provider
      state
      status
      street
      title
      connectors{
        id
        energyUnit
        kwhPrice
        plugType
        power
      }
    }
  }
}

# Response
{
  "data": {
    "getStations": {
      "found": "12",
      "stations": [
        {
          "id": "52ea9fcf-788d-4878-ad55-1e3434621723",
          "access": "Public",
          "address": "14061 Riverside Dr, Sherman Oaks, California, 91423, United States",
          "city": "Sherman Oaks",
          "country": "United States",
          "description": null,
          "distanceToStation": 0.3,
          "distanceUnit": "mi",
          "latitude": 34.157922,
          "longitude": -118.439487,
          "openingHours": "24 hours daily",
          "phoneNumber": null,
          "postcode": "91423",
          "provider": "Shell Recharge",
          "state": "California",
          "status": "Available",
          "street": "14061 Riverside Dr",
          "title": "DS-73",
          "connectors": [
            {
              "id": "ed80854e-ce16-4fa1-b18f-52f7641019e3",
              "energyUnit": null,
              "kwhPrice": null,
              "plugType": "CHAdeMO",
              "power": null
            },
            {
              "id": "715eb34d-ba05-4b64-914d-7c8e1e4fc08b",
              "energyUnit": null,
              "kwhPrice": null,
              "plugType": "CCS",
              "power": null
            }
          ]
        },
        {
          "id": "3e5ca523-e9ce-4fa9-8783-4d11c071d661",
          "access": "Public",
          "address": "14049 Ventura Blvd, Sherman Oaks, California, 91423, United States",
          "city": "Sherman Oaks",
          "country": "United States",
          "description": null,
          "distanceToStation": 0.56,
          "distanceUnit": "mi",
          "latitude": 34.14994,
          "longitude": -118.43972,
          "openingHours": "24 hours daily",
          "phoneNumber": null,
          "postcode": "91423",
          "provider": "Electrify America",
          "state": "California",
          "status": "Available",
          "street": "14049 Ventura Blvd",
          "title": "Ralph's 222 Ventura Blvd",
          "connectors": [
            {
              "id": "83dbb240-b428-40c1-8650-a2f83d55759d",
              "energyUnit": null,
              "kwhPrice": null,
              "plugType": "CHAdeMO",
              "power": null
            },
            {
              "id": "5d718276-72d6-4266-8df4-bcbeae439a67",
              "energyUnit": null,
              "kwhPrice": null,
              "plugType": "CCS",
              "power": null
            }
          ]
        },
......
