query getStations {
  getStations(
    filters: {
      latitude: 34.156839
      longitude: -118.434454
      distanceUnit: "mi"
      distanceRadius: 5
      plugTypes: ["CHAdeMO", "CCS"]
    },
     sortBy: {
      distanceToStation: "asc"
    },
    pagination: {
      size: 10
      from: 0
    }
  ){
    found
    stations{
      id
      access
      address
      city
      country
      description
      distanceToStation
      distanceUnit
      latitude
      longitude
      openingHours
      phoneNumber
      postcode
      provider
      state
      status
      street
      title
      connectors{
        id
        energyUnit
        kwhPrice
        plugType
        power
      }
    }
  }
}
