# Request

mutation userLogin {
  userLogin(
    email: "dev@estations.io"
    password: "password"
  ){
    authenticatable{
      email
    }
    credentials{
      accessToken
      client
      expiry
      tokenType
      uid
    }
  }
}

# Response with credentials details you would use in later requests to the eStations API.

{
  "data": {
    "userLogin": {
      "authenticatable": {
        "email": "dev@estations.io"
      },
      "credentials": {
        "accessToken": "OvZRVbA011HisJRjCAcNhA",
        "client": "q6ZRz4ib0LlMZWT-KbTJJg",
        "expiry": 1672763368,
        "tokenType": "Bearer",
        "uid": "dev@estations.io"
      }
    }
  }
}

# If email address or password is incorrect you will receive error message.

{
  "data": {
    "userLogin": null
  },
  "errors": [
    {
      "message": "Invalid login credentials. Please try again.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "userLogin"
      ],
      "extensions": {
        "code": "USER_ERROR"
      }
    }
  ]
}
