
{
  "data": {
    "userLogin": {
      "authenticatable": {
        "email": "dev@estations.io"
      },
      "credentials": {
        "accessToken": "OvZRVbA011HisJRjCAcNhA",
        "client": "q6ZRz4ib0LlMZWT-KbTJJg",
        "expiry": 1672763368, # expires in 1h
        "tokenType": "Bearer",
        "uid": "dev@estations.io" # your account email address
      }
    }
  }
}
