mutation userLogin {
  userLogin(
    email: "dev@estations.io"
    password: "password"
  ){
    authenticatable{
      email
    }
    credentials{
      accessToken
      client
      expiry
      tokenType
      uid
    }
  }
}
